version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "PR: waiting for review"
      - "PR: dependencies"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "PR: waiting for review"
      - "PR: dependencies"
    groups:
      babel:
        patterns:
          - "@babel/*"
          - "babel-*"
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
      rollup:
        patterns:
          - "rollup"
          - "@rollup/*"
